name = "Firm_Speech"
uuid = "1366b6a0-a754-48b3-8ed0-e722b2ccdba6"
version = "1.0.0-DEV"
authors = ["Christian Bustamante <cbustaam@gmail.com> and contributors"]

[deps]
Lib_Julia_Econ = "50e02c98-9e02-494d-aa48-19397f072af1"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
